// Lenz answers /review in two shapes. Of the fields this add-on reads, these differ:
//   - what failed: `failure.code` (current) or `failure.failure_reason` (older), on the review and on a
//     claim's deep check; "nothing checkable" is `no_checkable_claim` (current) where the older answer
//     said `no_claim` on a review and `not_a_claim` on a deep check;
//   - a quick check with no verdict: `verdict` null (current) or "Error" (older);
//   - the wait on a 429: `retry_after` (current) or `retry_after_seconds` / `reset_in_seconds` (older).
// fixtures/api-shapes/<shape>.<case>.json hold the same answer in each shape ({status, body}).
// expected.<case>.json is what the add-on produced from the older answer BEFORE it read the current
// shape (frozen; not regenerated by this code). Both shapes must still produce exactly that.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const LenzView = require('../src/view.js');
const LenzApi = require('../src/api.js');

const DIR = path.join(__dirname, 'fixtures', 'api-shapes');
const read = (file) => JSON.parse(fs.readFileSync(path.join(DIR, file), 'utf8'));
const exists = (file) => fs.existsSync(path.join(DIR, file));
const CASES = fs.readdirSync(DIR)
  .filter((f) => f.startsWith('expected.'))
  .map((f) => f.slice('expected.'.length, -'.json'.length))
  .sort();

// What the oracle recorded for one answer, produced by the current code.
function produce(name, r) {
  if (name.startsWith('get_')) {
    return { build: LenzView.build(r.body), buildDone: LenzView.build(r.body, { done: true }) };
  }
  return { describeError: LenzApi.describeError(r.status, {}, JSON.stringify(r.body)) };
}

// Serialized equality: what JSON keeps is exactly what the frozen oracle holds.
const same = (actual, expected) => assert.equal(JSON.stringify(actual, null, 2) + '\n', expected);

test('every case has a frozen expectation and a legacy answer', () => {
  assert.ok(CASES.length >= 12, CASES.join(','));
  for (const name of CASES) assert.ok(exists('legacy.' + name + '.json'), name);
});

for (const name of CASES) {
  const expected = fs.readFileSync(path.join(DIR, 'expected.' + name + '.json'), 'utf8');
  test('older answer gives what it gave before: ' + name, () => {
    same(produce(name, read('legacy.' + name + '.json')), expected);
  });
  if (exists('canonical.' + name + '.json')) {
    test('current answer gives what the older one gave: ' + name, () => {
      same(produce(name, read('canonical.' + name + '.json')), expected);
    });
  }
}

test('nothing checkable on a review: the current word reads as the older review word', () => {
  const canonical = read('canonical.get_failed_no_claim.json');
  assert.equal(canonical.body.failure.code, 'no_checkable_claim');
  assert.match(LenzView.build(canonical.body).failure, /no factual claim/);
  // The older answer's `not_a_claim` on a review was never the no-claim words; it still is not.
  const older = read('legacy.get_failed_not_a_claim.json');
  assert.match(LenzView.build(older.body).failure, /on our side/);
});

test('a row with no verdict never shows the hint inside its failure block', () => {
  const canonical = read('canonical.get_queued_row_failure_hint.json');
  const row = canonical.body.claims[1].assessment;
  assert.equal(row.status, 'queued');
  assert.ok(row.failure.hint);
  const e = LenzView.build(canonical.body, { done: true }).groups.flatMap((g) => g.entries).find((x) => x.id === 'claim:1');
  assert.equal(e.label, 'Not checked');
  assert.deepEqual(e.lines, [{ lead: null, text: 'Could not be checked this time.' }]);
});

test('a deep check stopped by a search outage is named so in both shapes', () => {
  for (const shape of ['legacy', 'canonical']) {
    const r = read(shape + '.get_deep_research_unavailable.json');
    const e = LenzView.build(r.body, { done: true }).groups.flatMap((g) => g.entries).find((x) => x.id === 'claim:2');
    assert.ok(e.lines.some((l) => /search was unavailable/.test(l.text)), shape);
  }
});

test('the body wait is read under every name when no Retry-After header came', () => {
  const d = (code, body) => LenzApi.describeError(code, {}, JSON.stringify(body)).retryAfterS;
  assert.equal(d(429, { code: 'review_in_flight', retry_after: 41 }), 41);
  assert.equal(d(429, { code: 'review_in_flight', retry_after_seconds: 42 }), 42);
  assert.equal(d(429, { code: 'extract_daily_limit', retry_after: 43 }), 43);
  assert.equal(d(429, { code: 'extract_daily_limit', reset_in_seconds: 44 }), 44);
  // The header still comes first.
  assert.equal(LenzApi.describeError(429, { 'Retry-After': '7' }, JSON.stringify({ code: 'review_in_flight', retry_after: 41 })).retryAfterS, 7);
});
