"""Writes test/fixtures/parity/basic.docx, the .docx twin of hand-parity-basic.json.

Stdlib only: `python3 scripts/build-parity-docx.py`. The expected text, basic.txt, is what Lenz's own
.docx reader gives for it (regenerated by Lenz). Change both fixtures together.
"""

import pathlib
import zipfile

OUT = pathlib.Path(__file__).resolve().parent.parent / 'test' / 'fixtures' / 'parity' / 'basic.docx'

W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'


def t(text: str) -> str:
    return f'<w:r><w:t xml:space="preserve">{text}</w:t></w:r>'


def p(*runs: str) -> str:
    return '<w:p>' + ''.join(runs) + '</w:p>'


def link(rid: str, text: str) -> str:
    return f'<w:hyperlink r:id="{rid}">{t(text)}</w:hyperlink>'


TAB = '<w:r><w:tab/></w:r>'
BR = '<w:r><w:br/></w:r>'

BODY = ''.join([
    p(t('Alpha beta.')),
    p(),
    p(t('Tab'), TAB, t('here and a soft break:'), BR, t('second line.')),
    p(t('See '), link('rId10', 'the report'), t(', then '), link('rId11', 'write'), t('.')),
    '<w:tbl><w:tr>'
    f'<w:tc>{p(t("Cell A"))}</w:tc>'
    f'<w:tc>{p(t("Cell B"))}{p(t("Cell B2"))}</w:tc>'
    '</w:tr></w:tbl>',
    p(TAB),
    p(t('End with émoji 🎉')),
])

DOCUMENT = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    f'<w:document xmlns:w="{W}" xmlns:r="{R}"><w:body>{BODY}<w:sectPr/></w:body></w:document>'
)

RELS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId10" TargetMode="External" '
    'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" '
    'Target="https://example.org/report?a=1&amp;b=2"/>'
    '<Relationship Id="rId11" TargetMode="External" '
    'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" '
    'Target="mailto:info@example.org"/>'
    '</Relationships>'
)

ROOT_RELS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" '
    'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
    'Target="word/document.xml"/>'
    '</Relationships>'
)

CONTENT_TYPES = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/word/document.xml" '
    'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
    '</Types>'
)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fixed = (1980, 1, 1, 0, 0, 0)  # a stable zip, so a rebuild with no change is no diff
    with zipfile.ZipFile(OUT, 'w', zipfile.ZIP_DEFLATED) as z:
        for name, data in [
            ('[Content_Types].xml', CONTENT_TYPES),
            ('_rels/.rels', ROOT_RELS),
            ('word/document.xml', DOCUMENT),
            ('word/_rels/document.xml.rels', RELS),
        ]:
            z.writestr(zipfile.ZipInfo(name, fixed), data.encode('utf-8'), zipfile.ZIP_DEFLATED)
    print(OUT)


if __name__ == '__main__':
    main()
